- partner: vaquita
  account: nonprod
  environment: qa

- partner: vaquita
  account: prod
  environment: live

- partner: wiztec
  account: nonprod
  environment: qa

- partner: wiztec
  account: prod
  environment: live
