name: Matrix Generator
description: Generates a matrix for well defined accounts and environments

inputs:
  partner:
    description: Partner to filter
    required: false
  environment:
    description: Environment to filter
    required: false

outputs:
  partner:
    description: Partner identifier
  environment:
    description: Environment identifier
  account:
    description: Account identifier
  role:
    description: Role identifier
  matrix:
    description: Matrix of partners and environments

runs:
  using: 'node16'
  main: 'dist/index.js'
