name: Terraform Plan All

on:
  pull_request_target:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: matrix
        name: Matrix
        uses: ./.github/actions/matrix

  plan:
    name: '${{ matrix.partner }}'
    needs: generate
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.generate.outputs.matrix) }}
    uses: ./.github/workflows/terraform_plan.yaml
    with:
      partner: ${{ matrix.partner }}
      environment: ${{ matrix.environment }}
      ref: ${{ github.event.pull_request.head.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
