name: Terraform Plan All

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: matrix
        name: Matrix
        uses: ./.github/actions/matrix

  plan:
    name: '${{ matrix.partner }}'
    needs: generate
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.generate.outputs.matrix) }}
    uses: ./.github/workflows/terraform_plan.yaml
    with:
      partner: ${{ matrix.partner }}
      environment: ${{ matrix.environment }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  results:
    name: Results
    needs:
      - generate
      - plan
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.generate.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ toJSON(needs.plan.outputs.result) }}
