name: Terraform Apply All

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     label: ${{ github.events.pull_request.labels.*.name }}
    steps:
      - name: Test
        run: |
          echo 'Context: ${{ toJSON(github) }}'
          echo 'Labels: ${{ toJSON(github.events.pull_request.labels.*.name) }}'
          # echo 'Running for label "${{ matrix.label }}"'
