name: Terraform Apply All

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        name: Matrix
        run: |
          json='${{ toJSON(github.event.pull_request.labels.*.name) }}'
          outputs=$(echo "${json}" | jq -c '[ .[] | select(startswith("deploy/")) | capture("(?<partner>[a-z]+)/(?<environment>[a-z]+)") ]')
          echo "matrix=$outputs" >> $GITHUB_OUTPUT

  apply:
    name: Apply
    needs: generate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.generate.outputs.matrix) }}
    steps:
      - name: Test
        run: |
          echo 'Running for label "${{ matrix.partner }}@${{ matrix.environment }}"'
