name: Terraform Apply All

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  generate:
    if: github.event.pull_request.merged == true
    name: Generate
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: matrix
        name: Matrix
        uses: ./.github/actions/matrix

  apply:
    name: '${{ matrix.partner }}'
    needs: generate
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.generate.outputs.matrix) }}
    uses: ./.github/workflows/terraform_apply.yaml
    with:
      partner: ${{ matrix.partner }}
      environment: ${{ matrix.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
