name: Terraform Apply All

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        label: ${{ github.event.pull_request.labels.*.name }}
    steps:
      - name: Test
        run: |
          echo 'Running for label "${{ matrix.label }}"'
