name: Terraform Validation
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format
        uses: dflook/terraform-fmt-check@v1

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: terraform validate
        uses: dflook/terraform-validate@v1
