name: Terraform Validation
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_wrapper: false
      - name: Terraform Format
        run: terraform fmt -check -diff
