name: Terraform Apply

on:
  workflow_call:
    inputs:
      partner:
        type: string
        required: true
      environment:
        type: string
        required: true
      ref:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  apply:
    name: '${{ inputs.environment }}'
    environment: '${{ inputs.partner }}/${{ inputs.environment }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - id: settings
        name: Get partner settings
        uses: ./.github/actions/matrix
        with:
          partner: ${{ inputs.partner }}
          environment: ${{ inputs.environment }}
      - name: Debug
        run: |
          echo "Partner: ${{ steps.settings.outputs.partner }}"
          echo "Region: ${{ steps.settings.outputs.region }}"
          echo "Environment: ${{ steps.settings.outputs.environment }}"
          echo "Role: ${{ steps.settings.outputs.role }}"
      - name: Assume IAM Role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ steps.settings.outputs.role }}
      - name: Ensure Workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          workspace: ${{ steps.settings.outputs.environment }}
          backend_config: 'key=${{ github.repository }}/${{ inputs.partner }}'
      - id: apply
        name: Terraform Apply
        uses: dflook/terraform-apply@v1
        with:
          label: '${{ inputs.partner }} ${{ inputs.environment }}'
          workspace: ${{ steps.settings.outputs.environment }}
          backend_config: 'key=${{ github.repository }}/${{ inputs.partner }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
