name: Testing
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: matrix
        name: Matrix
        uses: ./.github/actions/matrix

  test:
    name: Test
    needs: generate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.generate.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: settings
        name: Get settings
        uses: ./.github/actions/matrix
        with:
          partner: ${{ matrix.partner }}
          environment: ${{ matrix.environment }}
      - name: Debug
        run: |
          echo "Partner: ${{ steps.settings.outputs.partner }}"
          echo "Account: ${{ steps.settings.outputs.account }}"
          echo "Environment: ${{ steps.settings.outputs.environment }}"
          echo "Role: ${{ steps.settings.outputs.role }}"
